### ISSUE TITLE
main.dll

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#22] opened 2024-11-25 10:51 UTC
When I compile the client file, if I use the main.dll file in Debug, I can enter the game normally, but when I use the main.dll file in Release to log in to the game character, it will crash. The version I'm using is 15.9.67

**Comment by nicomuratona** [comment] 2024-11-26 11:37
The problem is in the Window.cpp file, in the `ChangeWindowText` function. The array is going out of scope before being processed by the window to set the name, that's why it fails. If you delete the `char text[256];` variable and define it as an instance member of the class CWindow, that problem is fixed.
In the next update i'm working no its already fixed but i didn't have time to finish the update yet. I'm working to add some systems too.

**Closed** 2024-11-27 02:39 UTC
